//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxySwitcher.Actions.DefaultActions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DefaultResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProxySwitcher.Actions.DefaultActions.DefaultResources", typeof(DefaultResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Default Printer.
        /// </summary>
        public static string ChangePrinter_Name {
            get {
                return ResourceManager.GetString("ChangePrinter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change default printer to:.
        /// </summary>
        public static string ChangePrinterTo_Label {
            get {
                return ResourceManager.GetString("ChangePrinterTo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper File:.
        /// </summary>
        public static string ChangeWallpaper_File {
            get {
                return ResourceManager.GetString("ChangeWallpaper_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Wallpaper.
        /// </summary>
        public static string ChangeWallpaper_Name {
            get {
                return ResourceManager.GetString("ChangeWallpaper_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string ChangeWallpaper_SelectFile {
            get {
                return ResourceManager.GetString("ChangeWallpaper_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        public static string ChangeWallpaper_Style {
            get {
                return ResourceManager.GetString("ChangeWallpaper_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string ChangeWallpaper_Style_Center {
            get {
                return ResourceManager.GetString("ChangeWallpaper_Style_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        public static string ChangeWallpaper_Style_Fill {
            get {
                return ResourceManager.GetString("ChangeWallpaper_Style_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit.
        /// </summary>
        public static string ChangeWallpaper_Style_Fit {
            get {
                return ResourceManager.GetString("ChangeWallpaper_Style_Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch.
        /// </summary>
        public static string ChangeWallpaper_Style_Stretch {
            get {
                return ResourceManager.GetString("ChangeWallpaper_Style_Stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile.
        /// </summary>
        public static string ChangeWallpaper_Style_Tile {
            get {
                return ResourceManager.GetString("ChangeWallpaper_Style_Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Proxy (Firefox).
        /// </summary>
        public static string DisableFirefox {
            get {
                return ResourceManager.GetString("DisableFirefox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Proxy (IE).
        /// </summary>
        public static string DisableIE8 {
            get {
                return ResourceManager.GetString("DisableIE8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Proxy (Opera).
        /// </summary>
        public static string DisableOpera {
            get {
                return ResourceManager.GetString("DisableOpera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: my_script.exe {0}.
        /// </summary>
        public static string ExecuteScript_ExampleText {
            get {
                return ResourceManager.GetString("ExecuteScript_ExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Script.
        /// </summary>
        public static string ExecuteScript_Name {
            get {
                return ResourceManager.GetString("ExecuteScript_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as administrator (shows UAC prompt).
        /// </summary>
        public static string ExecuteScript_RunAsAdmin_Checkbox {
            get {
                return ResourceManager.GetString("ExecuteScript_RunAsAdmin_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;All&gt;.
        /// </summary>
        public static string Firefox_All {
            get {
                return ResourceManager.GetString("Firefox_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this action to switch the proxy settings for Firefox.
        /// </summary>
        public static string Firefox_Description {
            get {
                return ResourceManager.GetString("Firefox_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Folder:.
        /// </summary>
        public static string Firefox_ProfileFolder {
            get {
                return ResourceManager.GetString("Firefox_ProfileFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Profile.
        /// </summary>
        public static string Firefox_ProfileSelectorTitle {
            get {
                return ResourceManager.GetString("Firefox_ProfileSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to refresh the profiles.
        /// </summary>
        public static string Firefox_RefreshProfiles {
            get {
                return ResourceManager.GetString("Firefox_RefreshProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Profile....
        /// </summary>
        public static string Firefox_SelectProfile_Button {
            get {
                return ResourceManager.GetString("Firefox_SelectProfile_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Profile to Switch:.
        /// </summary>
        public static string Firefox_SelectProfileToSwitch {
            get {
                return ResourceManager.GetString("Firefox_SelectProfileToSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this action to switch the proxy settings for Opera (Version 10 and above).
        /// </summary>
        public static string Opera_Description {
            get {
                return ResourceManager.GetString("Opera_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &quot;Exceptions&quot; format.
        /// </summary>
        public static string ProxyExceptionsError {
            get {
                return ResourceManager.GetString("ProxyExceptionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh_Button {
            get {
                return ResourceManager.GetString("Refresh_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save_Button {
            get {
                return ResourceManager.GetString("Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Saved_Status {
            get {
                return ResourceManager.GetString("Saved_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script:.
        /// </summary>
        public static string Script_Label {
            get {
                return ResourceManager.GetString("Script_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Dial-Up:.
        /// </summary>
        public static string UseDialUp_Checkbox {
            get {
                return ResourceManager.GetString("UseDialUp_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with network ID as parameter.
        /// </summary>
        public static string WithParameter_Checkbox {
            get {
                return ResourceManager.GetString("WithParameter_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use network name instead of the ID.
        /// </summary>
        public static string WithParameterName_Checkbox {
            get {
                return ResourceManager.GetString("WithParameterName_Checkbox", resourceCulture);
            }
        }
    }
}
