//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaUpdateAction {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DefaultResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SocialMediaUpdateAction.DefaultResources", typeof(DefaultResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel_Button {
            get {
                return ResourceManager.GetString("Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the Facebook icon to enable Facebook integration..
        /// </summary>
        public static string EnableFacebook_Label {
            get {
                return ResourceManager.GetString("EnableFacebook_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the Twitter icon to enable Twitter integration..
        /// </summary>
        public static string EnableTwitter_Label {
            get {
                return ResourceManager.GetString("EnableTwitter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySite URL:.
        /// </summary>
        public static string MySiteUrl_Label {
            get {
                return ResourceManager.GetString("MySiteUrl_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your MySite is located under &quot;https://sharepointURL/my/default.aspx&quot; then use the following URL: &quot;https://sharepointURL&quot;..
        /// </summary>
        public static string MySiteUrl_ToolTip {
            get {
                return ResourceManager.GetString("MySiteUrl_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save_Button {
            get {
                return ResourceManager.GetString("Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Saved_Status {
            get {
                return ResourceManager.GetString("Saved_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media Update.
        /// </summary>
        public static string SocialMediaActionName {
            get {
                return ResourceManager.GetString("SocialMediaActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Message:.
        /// </summary>
        public static string StatusMessage_Label {
            get {
                return ResourceManager.GetString("StatusMessage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate.
        /// </summary>
        public static string TWAuthenticate_Button {
            get {
                return ResourceManager.GetString("TWAuthenticate_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on Login in step 1. In the Browser window login with your Twitter account and click on &quot;Allow&quot; for this application. Copy the PIN and enter it in step 2..
        /// </summary>
        public static string TWDescription_Label {
            get {
                return ResourceManager.GetString("TWDescription_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login &amp; Get PIN.
        /// </summary>
        public static string TWLoginAndPin_Button {
            get {
                return ResourceManager.GetString("TWLoginAndPin_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN:.
        /// </summary>
        public static string TWPIN_Label {
            get {
                return ResourceManager.GetString("TWPIN_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1.
        /// </summary>
        public static string TWStep1_GroupBox {
            get {
                return ResourceManager.GetString("TWStep1_GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2.
        /// </summary>
        public static string TWStep2_GroupBox {
            get {
                return ResourceManager.GetString("TWStep2_GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Facebook.
        /// </summary>
        public static string UpdateFacebook_Checkbox {
            get {
                return ResourceManager.GetString("UpdateFacebook_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MySite update only works if this computer is joined to the domain and you are logged-in with your domain user account..
        /// </summary>
        public static string UpdateMySite_ToolTip {
            get {
                return ResourceManager.GetString("UpdateMySite_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update SharePoint 2010 MySite.
        /// </summary>
        public static string UpdateSharePoint_Checkbox {
            get {
                return ResourceManager.GetString("UpdateSharePoint_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Twitter.
        /// </summary>
        public static string UpdateTwitter_Checkbox {
            get {
                return ResourceManager.GetString("UpdateTwitter_Checkbox", resourceCulture);
            }
        }
    }
}
