//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxySwitcher.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProxySwitcher.Core.Resources.LanguageResources", typeof(LanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Label {
            get {
                return ResourceManager.GetString("About_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action has nothing to configure..
        /// </summary>
        public static string ActionHasNoConfig {
            get {
                return ResourceManager.GetString("ActionHasNoConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected action seems to be no longer available. Make sure the corresponding AddIn is available in the AddIns folder or delete this action from the network configuration..
        /// </summary>
        public static string ActionMissing {
            get {
                return ResourceManager.GetString("ActionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions_Label {
            get {
                return ResourceManager.GetString("Actions_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active_Checkbox {
            get {
                return ResourceManager.GetString("Active_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Action.
        /// </summary>
        public static string AddAction_Button {
            get {
                return ResourceManager.GetString("AddAction_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with one or more AddIns. Uninstall the last installed AddIn(s) and try again. Also make sure you have installed the correct version of the AddIn for this version of Proxy Switcher ({0})..
        /// </summary>
        public static string AddInLoadError {
            get {
                return ResourceManager.GetString("AddInLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;All Network Interfaces&gt;.
        /// </summary>
        public static string AllNetworkInterfaces_ComboBox {
            get {
                return ResourceManager.GetString("AllNetworkInterfaces_ComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Application_Label {
            get {
                return ResourceManager.GetString("Application_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically start with Windows.
        /// </summary>
        public static string AutoStart_CheckBox {
            get {
                return ResourceManager.GetString("AutoStart_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Switching.
        /// </summary>
        public static string AutoSwitching_Menu {
            get {
                return ResourceManager.GetString("AutoSwitching_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically check for updates.
        /// </summary>
        public static string CheckForUpdates_CheckBox {
            get {
                return ResourceManager.GetString("CheckForUpdates_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration_Label {
            get {
                return ResourceManager.GetString("Configuration_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Network.
        /// </summary>
        public static string DeactivateNode_Name {
            get {
                return ResourceManager.GetString("DeactivateNode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Action.
        /// </summary>
        public static string DeleteAction_Button {
            get {
                return ResourceManager.GetString("DeleteAction_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Network.
        /// </summary>
        public static string DeleteNetwork_Button {
            get {
                return ResourceManager.GetString("DeleteNetwork_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the network &apos;{0}&apos;?.
        /// </summary>
        public static string DeleteNetworkAreYouSure {
            get {
                return ResourceManager.GetString("DeleteNetworkAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate_Button {
            get {
                return ResourceManager.GetString("Donate_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal.
        /// </summary>
        public static string Donate_Label {
            get {
                return ResourceManager.GetString("Donate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit_Menu {
            get {
                return ResourceManager.GetString("Exit_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find more Actions.
        /// </summary>
        public static string FindMoreActions_Button {
            get {
                return ResourceManager.GetString("FindMoreActions_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Tab {
            get {
                return ResourceManager.GetString("Home_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network &apos;{0}&apos; is activated.
        /// </summary>
        public static string IsNowActivated {
            get {
                return ResourceManager.GetString("IsNowActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Language_Label {
            get {
                return ResourceManager.GetString("Language_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Switcher is Copyright 2012 Marco Wiedemeyer &lt;support@proxyswitcher.net&gt;.
        ///
        ///Proxy Switcher is freeware and can be distributed freely as long as it is not
        ///modified. It can be used free of charge for personal and commercial use.
        ///
        ///When you use this software you do so at your own risk. The author is 
        ///not responsible for any loss or damage resulting from the use or 
        ///misuse of this software..
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Network.
        /// </summary>
        public static string ManualSwitch_Menu {
            get {
                return ResourceManager.GetString("ManualSwitch_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method:.
        /// </summary>
        public static string Method_Label {
            get {
                return ResourceManager.GetString("Method_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name_Label {
            get {
                return ResourceManager.GetString("Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS suffix contains.
        /// </summary>
        public static string NetworkConfigurationMethod_DNSSuffix {
            get {
                return ResourceManager.GetString("NetworkConfigurationMethod_DNSSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docking Station (1=docked, 0=undocked).
        /// </summary>
        public static string NetworkConfigurationMethod_DockingStationState {
            get {
                return ResourceManager.GetString("NetworkConfigurationMethod_DockingStationState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway address contains.
        /// </summary>
        public static string NetworkConfigurationMethod_Gateway {
            get {
                return ResourceManager.GetString("NetworkConfigurationMethod_Gateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway MAC contains.
        /// </summary>
        public static string NetworkConfigurationMethod_GatewayMAC {
            get {
                return ResourceManager.GetString("NetworkConfigurationMethod_GatewayMAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address contains.
        /// </summary>
        public static string NetworkConfigurationMethod_IP {
            get {
                return ResourceManager.GetString("NetworkConfigurationMethod_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Location.
        /// </summary>
        public static string NetworkConfigurationMethod_Location {
            get {
                return ResourceManager.GetString("NetworkConfigurationMethod_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following server is reachable by ping.
        /// </summary>
        public static string NetworkConfigurationMethod_ServerAvailable {
            get {
                return ResourceManager.GetString("NetworkConfigurationMethod_ServerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WLAN SSID: Not connected but available.
        /// </summary>
        public static string NetworkConfigurationMethod_WLANAvailable {
            get {
                return ResourceManager.GetString("NetworkConfigurationMethod_WLANAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WLAN SSID: Connected.
        /// </summary>
        public static string NetworkConfigurationMethod_WLANSSID {
            get {
                return ResourceManager.GetString("NetworkConfigurationMethod_WLANSSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an *.ico or other image file to show when this network is active. Only *.ico files will be shown in the system tray..
        /// </summary>
        public static string NetworkIcon_ToolTip {
            get {
                return ResourceManager.GetString("NetworkIcon_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind to specific network interface:.
        /// </summary>
        public static string NetworkInterface_Label {
            get {
                return ResourceManager.GetString("NetworkInterface_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networks.
        /// </summary>
        public static string Networks_Label {
            get {
                return ResourceManager.GetString("Networks_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Network.
        /// </summary>
        public static string NewNetwork_Button {
            get {
                return ResourceManager.GetString("NewNetwork_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;New&gt;.
        /// </summary>
        public static string NewNetworkName {
            get {
                return ResourceManager.GetString("NewNetworkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup click does not create a new network.
        /// </summary>
        public static string NoNewNetwork_CheckBox {
            get {
                return ResourceManager.GetString("NoNewNetwork_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings.
        /// </summary>
        public static string OpenSettings_Button {
            get {
                return ResourceManager.GetString("OpenSettings_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string OpenSite_Button {
            get {
                return ResourceManager.GetString("OpenSite_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Switcher cannot run on this computer due to a company policy.
        ///
        ///If you have any questions, contact your system administrator..
        /// </summary>
        public static string PolicyDisabled {
            get {
                return ResourceManager.GetString("PolicyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query:.
        /// </summary>
        public static string Query_Label {
            get {
                return ResourceManager.GetString("Query_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Detect Network.
        /// </summary>
        public static string ReDetect_Menu {
            get {
                return ResourceManager.GetString("ReDetect_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Switcher must be restarted for changes to take effect..
        /// </summary>
        public static string RestartApplication {
            get {
                return ResourceManager.GetString("RestartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save_Button {
            get {
                return ResourceManager.GetString("Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Tab {
            get {
                return ResourceManager.GetString("Settings_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Saved.
        /// </summary>
        public static string SettingsSaved_Status {
            get {
                return ResourceManager.GetString("SettingsSaved_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show_Menu {
            get {
                return ResourceManager.GetString("Show_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Minimized.
        /// </summary>
        public static string StartMinimized_CheckBox {
            get {
                return ResourceManager.GetString("StartMinimized_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Switcher.
        /// </summary>
        public static string Startup_ToolTipText {
            get {
                return ResourceManager.GetString("Startup_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting network....
        /// </summary>
        public static string Status_Detecting {
            get {
                return ResourceManager.GetString("Status_Detecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network detection failed.
        /// </summary>
        public static string Status_DetectionFailed {
            get {
                return ResourceManager.GetString("Status_DetectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Status_Loading {
            get {
                return ResourceManager.GetString("Status_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop activating networks after one is detected.
        /// </summary>
        public static string StopAfterFirstMatch_CheckBox {
            get {
                return ResourceManager.GetString("StopAfterFirstMatch_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Network found
        ///(Click here to add it).
        /// </summary>
        public static string UnknownNetwork_Bubble {
            get {
                return ResourceManager.GetString("UnknownNetwork_Bubble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Network found.
        /// </summary>
        public static string UnknownNetwork_Bubble_NoNew {
            get {
                return ResourceManager.GetString("UnknownNetwork_Bubble_NoNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unknown network node cannot be deleted..
        /// </summary>
        public static string UnknownNetwork_CannotDelete {
            get {
                return ResourceManager.GetString("UnknownNetwork_CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this network if no other network settings apply..
        /// </summary>
        public static string UnknownNetworkDescription {
            get {
                return ResourceManager.GetString("UnknownNetworkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string Update_Button {
            get {
                return ResourceManager.GetString("Update_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer Version ({0}) is available.
        ///Do you want to visit the download page now?.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking....
        /// </summary>
        public static string UpdateInProgress_Button {
            get {
                return ResourceManager.GetString("UpdateInProgress_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Windows 7 Mode (show in taskbar and tasktray).
        /// </summary>
        public static string UseWin7Mode_CheckBox {
            get {
                return ResourceManager.GetString("UseWin7Mode_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Windows 7 Location API.
        /// </summary>
        public static string Win7LocationAPI_CheckBox {
            get {
                return ResourceManager.GetString("Win7LocationAPI_CheckBox", resourceCulture);
            }
        }
    }
}
