//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxySwitcher.Actions.ProxyBase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ActionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProxySwitcher.Actions.ProxyBase.ActionResources", typeof(ActionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use automatic configuration script.
        /// </summary>
        public static string AutoConfig_Checkbox {
            get {
                return ResourceManager.GetString("AutoConfig_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically detect settings.
        /// </summary>
        public static string AutoDetect_Checkbox {
            get {
                return ResourceManager.GetString("AutoDetect_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass proxy server for local addresses.
        /// </summary>
        public static string Bypass_Checkbox {
            get {
                return ResourceManager.GetString("Bypass_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions:.
        /// </summary>
        public static string Exceptions_Label {
            get {
                return ResourceManager.GetString("Exceptions_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use semicolons (;) to separate entries. For Firefox use commas (,) to separate entries..
        /// </summary>
        public static string Exceptions_ToolTip {
            get {
                return ResourceManager.GetString("Exceptions_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Password_Label {
            get {
                return ResourceManager.GetString("Password_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string Port_Label {
            get {
                return ResourceManager.GetString("Port_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy requires authentication.
        /// </summary>
        public static string RequiresAuthentication_Checkbox {
            get {
                return ResourceManager.GetString("RequiresAuthentication_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save_Button {
            get {
                return ResourceManager.GetString("Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Saved_Status {
            get {
                return ResourceManager.GetString("Saved_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string Type_Label {
            get {
                return ResourceManager.GetString("Type_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url:.
        /// </summary>
        public static string Url_Label {
            get {
                return ResourceManager.GetString("Url_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For automatic configuration script use the full URL (e.g. &quot;http://autoconf/conf.pac&quot;)
        ///Otherwise use the server name (e.g. &quot;proxyserver.com&quot;).
        /// </summary>
        public static string Url_ToolTip {
            get {
                return ResourceManager.GetString("Url_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string Username_Label {
            get {
                return ResourceManager.GetString("Username_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same for all protocols.
        /// </summary>
        public static string UseSame_Button {
            get {
                return ResourceManager.GetString("UseSame_Button", resourceCulture);
            }
        }
    }
}
